; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native]
platform = native
test_framework = googletest
build_flags =
    -fexceptions
build_unflags =
    -fno-exceptions

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
#test_framework = googletest
build_flags =
    -Ofast
    -mcpu=cortex-m4
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -fexceptions
build_unflags =
    -mfloat-abi=soft
    -fno-exceptions

[env]
build_flags =
    -fexceptions
build_unflags =
    -fno-exceptions
